# Image of the managed service-account instances
image: quay.io/haoqing/managed-serviceaccount
tag: latest
agentInstallAll: true

# Number of replicas
replicas: 1

enableAddOnDeploymentConfig: false

featureGates:
  ephemeralIdentity: false

agentImagePullSecret: ""
